CREATE TABLE bubble_financial_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id),
  wo_id TEXT NOT NULL,
  company TEXT,
  market TEXT,
  event_type TEXT NOT NULL,
  invoice_number TEXT,
  amount DECIMAL(12, 2),
  currency TEXT DEFAULT 'USD',
  vendor_name TEXT,
  payment_method TEXT,
  invoice_sent_at TIMESTAMPTZ,
  payment_received_at TIMESTAMPTZ,
  due_date DATE,
  aging_days INTEGER,
  bill_number TEXT,
  bill_created_at TIMESTAMPTZ,
  bill_approved_at TIMESTAMPTZ,
  bill_paid_at TIMESTAMPTZ,
  adjustment_reason TEXT,
  original_amount DECIMAL(12, 2),
  adjusted_amount DECIMAL(12, 2),
  metadata JSONB DEFAULT '{}',
  source TEXT DEFAULT 'webhook',
  bubble_thing_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
